### PR TITLE
WinRT compatibility

### PR DESCRIPTION
**Pull request by albertofustinoni**

### CODE REVIEW

**Comment by twinaphex** [comment]
BTW, you need to fix your usage of 'inline' inside that file_stream_transform.h file.

Turn it from 'inline' into 'static INLINE' instead.

**Comment by albertofustinoni** [comment]
@twinaphex Changed inline to static INLINE following your instructions

**Comment by twinaphex** [comment]
OK thanks. Is it still necessary for me to merge that PR you have in the Genesis Plus GX repo or not?

**Comment by albertofustinoni** [comment]
Thank you very much :)

**Pull request merged**
